<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_checkout.handler.exception' shared service.

return $this->services['ps_checkout.handler.exception'] = new \PrestaShop\Module\PrestashopCheckout\Handler\ExceptionHandler(($this->services['ps_checkout.module'] ?? $this->load('getPsCheckout_ModuleService.php')), ($this->services['ps_checkout.env.sentry'] ?? ($this->services['ps_checkout.env.sentry'] = new \PrestaShop\Module\PrestashopCheckout\Environment\SentryEnv())), ($this->services['ps_checkout.repository.prestashop.account'] ?? $this->load('getPsCheckout_Repository_Prestashop_AccountService.php')));
