<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFNDhCzK\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFNDhCzK/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerFNDhCzK.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerFNDhCzK\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerFNDhCzK\appAppKernelProdContainer([
    'container.build_hash' => 'FNDhCzK',
    'container.build_id' => 'e5d2dc95',
    'container.build_time' => 1695850490,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFNDhCzK');
