<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container90rX7MG\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container90rX7MG/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container90rX7MG.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container90rX7MG\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container90rX7MG\appAppKernelProdContainer([
    'container.build_hash' => '90rX7MG',
    'container.build_id' => '5fb66528',
    'container.build_time' => 1679859774,
], __DIR__.\DIRECTORY_SEPARATOR.'Container90rX7MG');
