<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_checkout.api.firebase.auth.factory' shared service.

return $this->services['ps_checkout.api.firebase.auth.factory'] = new \PrestaShop\Module\PrestashopCheckout\Api\Firebase\AuthFactory(($this->services['ps_checkout.api.firebase.auth'] ?? ($this->services['ps_checkout.api.firebase.auth'] = new \PrestaShop\Module\PrestashopCheckout\Api\Firebase\Auth())), ($this->services['ps_checkout.persistent.configuration'] ?? $this->load('getPsCheckout_Persistent_ConfigurationService.php')));
