<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_checkout.segment.tracker' shared service.

return $this->services['ps_checkout.segment.tracker'] = new \PrestaShop\Module\PrestashopCheckout\Segment\SegmentTracker(($this->services['ps_checkout.env.segmentenv'] ?? ($this->services['ps_checkout.env.segmentenv'] = new \PrestaShop\Module\PrestashopCheckout\Environment\SegmentEnv())), ($this->services['ps_checkout.manager.shopuuid'] ?? ($this->services['ps_checkout.manager.shopuuid'] = new \PrestaShop\Module\PrestashopCheckout\ShopUuidManager())));
