<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_checkout.updater.paypal.account' shared service.

return $this->services['ps_checkout.updater.paypal.account'] = new \PrestaShop\Module\PrestashopCheckout\Updater\PaypalAccountUpdater(($this->services['ps_checkout.persistent.configuration'] ?? $this->load('getPsCheckout_Persistent_ConfigurationService.php')), ($this->services['ps_checkout.paypal.provider.merchant_integration'] ?? $this->load('getPsCheckout_Paypal_Provider_MerchantIntegrationService.php')));
