<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_checkout.customer' shared service.

return $this->services['ps_checkout.customer'] = new \PrestaShop\Module\PrestashopCheckout\Customer(($this->services['ps_checkout.context.prestashop'] ?? ($this->services['ps_checkout.context.prestashop'] = new \PrestaShop\Module\PrestashopCheckout\Context\PrestaShopContext())));
