<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyD4bfHqwfQRIgzK4Kubj'."\n".'eC2rH+c7MQCo8PuHo72pl+PDHA34xp6QmieqmRiMFq3wzrvts2GdUS9ZEprDkTKf'."\n".'RTxXTG5sud4UmIHszCtgFjhiUcA3XcRBsE75hT2zDQmhzffgenzLaWtLSfETdcqO'."\n".'/USjofh8y+y843k4yEOAaOegIPmRAd99DyOMAZElH4nYRYMsD91/FkOJI0/pBNQ+'."\n".'OYWB4AVS+pEIT6LU/QV/RrRc6+RCRMLXKrwkW3Z+QLG34XSRJLP/+HHLPqPoJmMb'."\n".'8igSzaNRPP4+ktFIJFQLU0UQ5ieCSLjJXnHTNdYitf7BWQqUHgdWpi+5oFHlA5rs'."\n".'GQIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
