<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHgl1ebg\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHgl1ebg/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHgl1ebg.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHgl1ebg\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerHgl1ebg\appAppKernelDevDebugContainer([
    'container.build_hash' => 'Hgl1ebg',
    'container.build_id' => 'ab14b235',
    'container.build_time' => 1696859269,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHgl1ebg');
