<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOCU5OOx\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOCU5OOx/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOCU5OOx.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOCU5OOx\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerOCU5OOx\appAppKernelDevDebugContainer([
    'container.build_hash' => 'OCU5OOx',
    'container.build_id' => '720afd93',
    'container.build_time' => 1696878622,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOCU5OOx');
