<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOZL4oTU\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOZL4oTU/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOZL4oTU.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOZL4oTU\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerOZL4oTU\appAppKernelDevDebugContainer([
    'container.build_hash' => 'OZL4oTU',
    'container.build_id' => 'ca649ca4',
    'container.build_time' => 1696862979,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOZL4oTU');
