SELECT p.`id_product`  AS `id_product`,
 sa.`active`  AS `active`,
 pl.`name`  AS `name`,
 cl.`name`  AS `name_category`,
 sa.`price`  AS `price`,
 sa.`id_tax_rules_group` AS `tax_id`,
 sa.`wholesale_price` AS `wholesale_price`,
 p.`on_sale` AS `on_sale`,
 '' AS `discount_amount`,
 '' AS `discount_percent`,
 '' AS `discount_from`,
 '' AS `discount_to`,
 p.`reference`  AS `reference`,
 p.`id_supplier` AS `id_supplier`,
 '' AS `supplier`,
 '' AS `manufacturer`,
 p.`ean13` AS `ean13`,
 p.`upc` AS `upc`,
 p.`ecotax` AS `ecotax`,
 p.`width` AS `width`,
 p.`height` AS `height`,
 p.`depth` AS `depth`,
 p.`weight` AS `weight`,
 '' AS `delivery_in_stock_time`,
 '' AS `delivery_out_stock_time`,
 p.`quantity` AS `quantity`,
 p.`minimal_quantity` AS `minimal_quantity`,
 p.`low_stock_threshold` AS `low_stock_threshold`,
 p.`low_stock_alert` AS `low_stock_alert`,
 p.`visibility` AS `visibility`,
 p.`additional_shipping_cost` AS `additional_shipping_cost`,
 p.`unity` AS `unity`,
 p.`unit_price` AS `unit_price`,
 pl.`description_short` AS `description_short`,
 pl.`description` AS `description`,
 '' AS `tags`,
 pl.`meta_title` AS `meta_title`,
 pl.`meta_keywords` AS `meta_keywords`,
 pl.`meta_description` AS `meta_description`,
 pl.`link_rewrite` AS `link_rewrite`,
 pl.`delivery_in_stock` AS `text_when_in_stock`,
 pl.`delivery_out_stock` AS `text_when_out_stock`,
 p.`available_for_order` AS `available_for_order`,
 p.`available_date` AS `available_date`,
 '' AS `creation_date`,
 p.`show_price` AS `show_price`,
 '' AS `images_url`,
 '' AS `image_alt_text`,
 0 AS `delete_images`,
 '' AS `features`,
 p.`online_only` AS `online_only`,
 p.`condition` AS `condition`,
 p.`customizable` AS `customizable`,
 p.`uploadable_files` AS `uploadable_files`,
 p.`text_fields` AS `text_fields`,
 p.`out_of_stock` AS `out_of_stock`,
 p.`is_virtual` AS `is_virtual`,
 '' AS `file_url`,
 p.`uploadable_files` AS `uploadable_files`,
 '' AS `expiration_date`,
 '' AS `number_of_days`,
 shop.`name` AS `shop_name`,
 '' AS `advanced_stock_management`,
 '' AS `depends_on_stock`,
 '' AS `warehouse`,
 '' AS `acessories`
FROM  `ps_product` p 
 LEFT JOIN `ps_product_lang` pl ON (pl.`id_product` = p.`id_product` AND pl.`id_lang` = 1 AND pl.`id_shop` = 1) 
 LEFT JOIN `ps_stock_available` sav ON (sav.`id_product` = p.`id_product` AND sav.`id_product_attribute` = 0 AND sav.id_shop = 1  AND sav.id_shop_group = 0 ) 
 JOIN `ps_product_shop` sa ON (p.`id_product` = sa.`id_product` AND sa.id_shop = 1) 
 LEFT JOIN `ps_category_lang` cl ON (sa.`id_category_default` = cl.`id_category` AND cl.`id_lang` = 1 AND cl.id_shop = 1) 
 LEFT JOIN `ps_category` c ON (c.`id_category` = cl.`id_category`) 
 LEFT JOIN `ps_shop` shop ON (shop.id_shop = 1) 
 LEFT JOIN `ps_image_shop` image_shop ON (image_shop.`id_product` = p.`id_product` AND image_shop.`cover` = 1 AND image_shop.id_shop = 1) 
 LEFT JOIN `ps_image` i ON (i.`id_image` = image_shop.`id_image`) 
 LEFT JOIN `ps_product_download` pd ON (pd.`id_product` = p.`id_product`) 
WHERE (1 AND state = 1)
ORDER BY  `id_product` desc